function drawArrow(x, y, txt, props)
    % draws arrow marker on current axis
    h = annotation(gcf, 'textarrow', 'String', txt);
    set(h,'parent', gca, ...
    'position', [x(1),y(1),x(2)-x(1),y(2)-y(1)], ...
    'LineWidth', 1, 'HeadLength', 5, 'HeadWidth', 8, 'HeadStyle', 'cback1', ...
    props{:} );
end